# Generated by Django 5.2.8 on 2025-12-12 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arte', '0003_alter_arte_url_imagen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('recorrido', models.TextField(blank=True, null=True)),
                ('inicio_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('inicio_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('fin_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('fin_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('artes', models.ManyToManyField(related_name='rutas', to='arte.arte')),
                ('creador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
