# Generated by Django 5.2.8 on 2025-12-12 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='fin_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='fin_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='inicio_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='inicio_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
