# Generated by Django 5.2.8 on 2025-12-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arte', '0002_remove_arte_latitud_remove_arte_longitud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arte',
            name='url_imagen',
            field=models.ImageField(upload_to='imagenes/'),
        ),
    ]
