# Generated by Django 5.2.8 on 2025-12-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arte', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arte',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='arte',
            name='longitud',
        ),
        migrations.AddField(
            model_name='arte',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
